# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marcelo Alexandre
email: marcelobalexandre@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
default_locale: en
github_username: marcelobalexandre
twitter_username: marcelobalex
instagram_username: marcelobalexandre

defaults:
  -
    scope:
      path: _posts/en
      type: posts
    values:
      locale: en
      permalink: /blog/:title
  -
    scope:
      path: _posts/pt-BR
      type: posts
    values:
      locale: pt-BR
      permalink: /blog/pt-BR/:title

pagination:
  enabled: true
  per_page: 2
  locale: en

root_path:
  en: '/'
  pt-BR: '/pt-BR'

search_path:
  en: '/blog/search'
  pt-BR: '/pt-BR/blog/pesquisar'

header_links:
  en:
    - /
    - /blog/index.html
  pt-BR:
    - /pt-BR/index.html
    - /pt-BR/blog/index.html

categories_by_locale:
  en:
    - category_one
    - category_two
  pt-BR:
    - categoria_um
    - categoria_dois

tags_by_locale:
  en:
    - tag_one
    - tag_two
  pt-BR:
    - tag_um
    - tag_dois

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
